/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as PitchCodesRouteImport } from './routes/pitch.codes'
import { Route as PitchGameIdRouteImport } from './routes/pitch.$gameId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ScoutSummaryGameIdRouteImport } from './routes/scout.summary.$gameId'
import { Route as LearningSummarySessionIdRouteImport } from './routes/learning.summary.$sessionId'
import { Route as PitchGameIdBatterBatterKeyRouteImport } from './routes/pitch.$gameId.batter.$batterKey'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)
const PitchCodesRoute = PitchCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => PitchRoute,
} as any)
const PitchGameIdRoute = PitchGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => PitchRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutSummaryGameIdRoute = ScoutSummaryGameIdRouteImport.update({
  id: '/summary/$gameId',
  path: '/summary/$gameId',
  getParentRoute: () => ScoutRoute,
} as any)
const LearningSummarySessionIdRoute =
  LearningSummarySessionIdRouteImport.update({
    id: '/summary/$sessionId',
    path: '/summary/$sessionId',
    getParentRoute: () => LearningRoute,
  } as any)
const PitchGameIdBatterBatterKeyRoute =
  PitchGameIdBatterBatterKeyRouteImport.update({
    id: '/batter/$batterKey',
    path: '/batter/$batterKey',
    getParentRoute: () => PitchGameIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/development': typeof DevelopmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/pitch': typeof PitchRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scout': typeof ScoutRouteWithChildren
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/pitch/$gameId': typeof PitchGameIdRouteWithChildren
  '/pitch/codes': typeof PitchCodesRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/learning/summary/$sessionId': typeof LearningSummarySessionIdRoute
  '/scout/summary/$gameId': typeof ScoutSummaryGameIdRoute
  '/pitch/$gameId/batter/$batterKey': typeof PitchGameIdBatterBatterKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/development': typeof DevelopmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/pitch': typeof PitchRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scout': typeof ScoutRouteWithChildren
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/pitch/$gameId': typeof PitchGameIdRouteWithChildren
  '/pitch/codes': typeof PitchCodesRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/learning/summary/$sessionId': typeof LearningSummarySessionIdRoute
  '/scout/summary/$gameId': typeof ScoutSummaryGameIdRoute
  '/pitch/$gameId/batter/$batterKey': typeof PitchGameIdBatterBatterKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/development': typeof DevelopmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/pitch': typeof PitchRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scout': typeof ScoutRouteWithChildren
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/pitch/$gameId': typeof PitchGameIdRouteWithChildren
  '/pitch/codes': typeof PitchCodesRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/learning/summary/$sessionId': typeof LearningSummarySessionIdRoute
  '/scout/summary/$gameId': typeof ScoutSummaryGameIdRoute
  '/pitch/$gameId/batter/$batterKey': typeof PitchGameIdBatterBatterKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/development'
    | '/forgot-password'
    | '/learning'
    | '/login'
    | '/pitch'
    | '/profile'
    | '/reset-password'
    | '/scout'
    | '/signup'
    | '/teams'
    | '/invite/$token'
    | '/pitch/$gameId'
    | '/pitch/codes'
    | '/teams/$teamId'
    | '/learning/summary/$sessionId'
    | '/scout/summary/$gameId'
    | '/pitch/$gameId/batter/$batterKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/development'
    | '/forgot-password'
    | '/learning'
    | '/login'
    | '/pitch'
    | '/profile'
    | '/reset-password'
    | '/scout'
    | '/signup'
    | '/teams'
    | '/invite/$token'
    | '/pitch/$gameId'
    | '/pitch/codes'
    | '/teams/$teamId'
    | '/learning/summary/$sessionId'
    | '/scout/summary/$gameId'
    | '/pitch/$gameId/batter/$batterKey'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/development'
    | '/forgot-password'
    | '/learning'
    | '/login'
    | '/pitch'
    | '/profile'
    | '/reset-password'
    | '/scout'
    | '/signup'
    | '/teams'
    | '/invite/$token'
    | '/pitch/$gameId'
    | '/pitch/codes'
    | '/teams/$teamId'
    | '/learning/summary/$sessionId'
    | '/scout/summary/$gameId'
    | '/pitch/$gameId/batter/$batterKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DevelopmentRoute: typeof DevelopmentRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LearningRoute: typeof LearningRouteWithChildren
  LoginRoute: typeof LoginRoute
  PitchRoute: typeof PitchRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScoutRoute: typeof ScoutRouteWithChildren
  SignupRoute: typeof SignupRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/pitch/codes': {
      id: '/pitch/codes'
      path: '/codes'
      fullPath: '/pitch/codes'
      preLoaderRoute: typeof PitchCodesRouteImport
      parentRoute: typeof PitchRoute
    }
    '/pitch/$gameId': {
      id: '/pitch/$gameId'
      path: '/$gameId'
      fullPath: '/pitch/$gameId'
      preLoaderRoute: typeof PitchGameIdRouteImport
      parentRoute: typeof PitchRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/summary/$gameId': {
      id: '/scout/summary/$gameId'
      path: '/summary/$gameId'
      fullPath: '/scout/summary/$gameId'
      preLoaderRoute: typeof ScoutSummaryGameIdRouteImport
      parentRoute: typeof ScoutRoute
    }
    '/learning/summary/$sessionId': {
      id: '/learning/summary/$sessionId'
      path: '/summary/$sessionId'
      fullPath: '/learning/summary/$sessionId'
      preLoaderRoute: typeof LearningSummarySessionIdRouteImport
      parentRoute: typeof LearningRoute
    }
    '/pitch/$gameId/batter/$batterKey': {
      id: '/pitch/$gameId/batter/$batterKey'
      path: '/batter/$batterKey'
      fullPath: '/pitch/$gameId/batter/$batterKey'
      preLoaderRoute: typeof PitchGameIdBatterBatterKeyRouteImport
      parentRoute: typeof PitchGameIdRoute
    }
  }
}

interface LearningRouteChildren {
  LearningSummarySessionIdRoute: typeof LearningSummarySessionIdRoute
}

const LearningRouteChildren: LearningRouteChildren = {
  LearningSummarySessionIdRoute: LearningSummarySessionIdRoute,
}

const LearningRouteWithChildren = LearningRoute._addFileChildren(
  LearningRouteChildren,
)

interface PitchGameIdRouteChildren {
  PitchGameIdBatterBatterKeyRoute: typeof PitchGameIdBatterBatterKeyRoute
}

const PitchGameIdRouteChildren: PitchGameIdRouteChildren = {
  PitchGameIdBatterBatterKeyRoute: PitchGameIdBatterBatterKeyRoute,
}

const PitchGameIdRouteWithChildren = PitchGameIdRoute._addFileChildren(
  PitchGameIdRouteChildren,
)

interface PitchRouteChildren {
  PitchGameIdRoute: typeof PitchGameIdRouteWithChildren
  PitchCodesRoute: typeof PitchCodesRoute
}

const PitchRouteChildren: PitchRouteChildren = {
  PitchGameIdRoute: PitchGameIdRouteWithChildren,
  PitchCodesRoute: PitchCodesRoute,
}

const PitchRouteWithChildren = PitchRoute._addFileChildren(PitchRouteChildren)

interface ScoutRouteChildren {
  ScoutSummaryGameIdRoute: typeof ScoutSummaryGameIdRoute
}

const ScoutRouteChildren: ScoutRouteChildren = {
  ScoutSummaryGameIdRoute: ScoutSummaryGameIdRoute,
}

const ScoutRouteWithChildren = ScoutRoute._addFileChildren(ScoutRouteChildren)

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DevelopmentRoute: DevelopmentRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LearningRoute: LearningRouteWithChildren,
  LoginRoute: LoginRoute,
  PitchRoute: PitchRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScoutRoute: ScoutRouteWithChildren,
  SignupRoute: SignupRoute,
  TeamsRoute: TeamsRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
