/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoutSummaryGameIdRouteImport } from './routes/scout.summary.$gameId'
import { Route as LearningSummarySessionIdRouteImport } from './routes/learning.summary.$sessionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutSummaryGameIdRoute = ScoutSummaryGameIdRouteImport.update({
  id: '/summary/$gameId',
  path: '/summary/$gameId',
  getParentRoute: () => ScoutRoute,
} as any)
const LearningSummarySessionIdRoute =
  LearningSummarySessionIdRouteImport.update({
    id: '/summary/$sessionId',
    path: '/summary/$sessionId',
    getParentRoute: () => LearningRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/development': typeof DevelopmentRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRouteWithChildren
  '/signup': typeof SignupRoute
  '/learning/summary/$sessionId': typeof LearningSummarySessionIdRoute
  '/scout/summary/$gameId': typeof ScoutSummaryGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/development': typeof DevelopmentRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRouteWithChildren
  '/signup': typeof SignupRoute
  '/learning/summary/$sessionId': typeof LearningSummarySessionIdRoute
  '/scout/summary/$gameId': typeof ScoutSummaryGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/development': typeof DevelopmentRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRouteWithChildren
  '/signup': typeof SignupRoute
  '/learning/summary/$sessionId': typeof LearningSummarySessionIdRoute
  '/scout/summary/$gameId': typeof ScoutSummaryGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/development'
    | '/learning'
    | '/login'
    | '/profile'
    | '/scout'
    | '/signup'
    | '/learning/summary/$sessionId'
    | '/scout/summary/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/development'
    | '/learning'
    | '/login'
    | '/profile'
    | '/scout'
    | '/signup'
    | '/learning/summary/$sessionId'
    | '/scout/summary/$gameId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/development'
    | '/learning'
    | '/login'
    | '/profile'
    | '/scout'
    | '/signup'
    | '/learning/summary/$sessionId'
    | '/scout/summary/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DevelopmentRoute: typeof DevelopmentRoute
  LearningRoute: typeof LearningRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ScoutRoute: typeof ScoutRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/summary/$gameId': {
      id: '/scout/summary/$gameId'
      path: '/summary/$gameId'
      fullPath: '/scout/summary/$gameId'
      preLoaderRoute: typeof ScoutSummaryGameIdRouteImport
      parentRoute: typeof ScoutRoute
    }
    '/learning/summary/$sessionId': {
      id: '/learning/summary/$sessionId'
      path: '/summary/$sessionId'
      fullPath: '/learning/summary/$sessionId'
      preLoaderRoute: typeof LearningSummarySessionIdRouteImport
      parentRoute: typeof LearningRoute
    }
  }
}

interface LearningRouteChildren {
  LearningSummarySessionIdRoute: typeof LearningSummarySessionIdRoute
}

const LearningRouteChildren: LearningRouteChildren = {
  LearningSummarySessionIdRoute: LearningSummarySessionIdRoute,
}

const LearningRouteWithChildren = LearningRoute._addFileChildren(
  LearningRouteChildren,
)

interface ScoutRouteChildren {
  ScoutSummaryGameIdRoute: typeof ScoutSummaryGameIdRoute
}

const ScoutRouteChildren: ScoutRouteChildren = {
  ScoutSummaryGameIdRoute: ScoutSummaryGameIdRoute,
}

const ScoutRouteWithChildren = ScoutRoute._addFileChildren(ScoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DevelopmentRoute: DevelopmentRoute,
  LearningRoute: LearningRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ScoutRoute: ScoutRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
